name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Gradle Wrapper
        run: chmod +x ./gradlew

      #- name: Build with Gradle
        #run: ./gradlew build --no-daemon

      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV
          
      - name: list-projects
        run: |
          kdt list projects\

      - name:  linux-commands
        run: |
          ls 
          find ls
          wget https://github.com/Throw-in-can/kotlin-petclinic/blob/main/kotlin-cyclone.json 
          ls 

      - name: import-manual
        run: |
          kdt sbom import -p kotlin-petclinic -b main -f kotlin-cyclone.json
          
  
      - name: scan-manual
        run: |
          kdt scan -p kotlin-petclinic -t semgrep -b main --params=ruleset_options:owasp-top-ten --params=ruleset_types:0 --params=exclude:
      
      #- name: semgrep-Scan
       # run: |
        #  kdt scan\
         #   -p ${{ github.event.repository.name }} \
          #  -b main \
           # -t semgrep \
            #--params=ruleset_options:owasp-top-ten \
            #--params=ruleset_types:0 \
            #--params=exclude:
    
      - name: Import Sbom Results
        run: |
          kdt sbom import\
            -p ${{ github.event.repository.name }}\ 
            -b main\ 
            -f kotlin-cyclone.json
